// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  website: [{type: 'autogenerated', dirName: 'website'}],
  development: [{type: 'autogenerated', dirName: 'development'}],
};

module.exports = sidebars;
